version: "3.5"

services:

  bd:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=12345Abcde
      - MYSQL_DATABASE=dockerbox
      - MYSQL_USER=dockerbox
      - MYSQL_PASSWORD=12345Abcde
    volumes:
      - datos_mariadb:/var/lib/mysql
    expose:
      - 3306

  web:
    image: webdevops/php-apache-dev:7.3
    depends_on:
      - bd
    volumes:
      - ./www:/app
    expose:
      - 80
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - bd
    environment:
      - PMA_HOST=bd
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=12345Abcde
    ports:
      - 8080:80

volumes:
  datos_mariadb:
