version: "3.5"

services:

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
    environment:
      DOMAINS: >
        dockerbox.test -> http://nginx:80,
        phpmyadmin.dockerbox.test -> http://phpmyadmin:80,
        maildev.dockerbox.test -> http://maildev:80,
        ${EXTRA_SITES}
      CLIENT_MAX_BODY_SIZE: 1024M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - dockerbox.test
    depends_on:
      - nginx
      - phpmyadmin
      - maildev

  mariadb:
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - 3306

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx.dev
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./sites:/var/www/html:delegated
    expose:
      - 80
    depends_on:
      - php

  php:
    container_name: php
    hostname: php
    build:
      context: .
      dockerfile: Dockerfile.php.dev
      args:
        - PHP_VERSION=${PHP_VERSION}
        - ALPINE_VERSION=${ALPINE_VERSION}
    environment:
      - php.display_errors=on
      - php.error_reporting=E_ALL
      - PHP_XDEBUG_MODE=develop
      - PHP_XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
      - PHP_XDEBUG_REMOTE_PORT=9000
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=yes
      - PHP_XDEBUG_IDEKEY=docker
    volumes:
      - ./sites:/var/www/html:delegated
    depends_on:
      - mariadb
      - redis

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=https://phpmyadmin.dockerbox.test
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=1g
    volumes:
      - phpmyadmin_sessions:/sessions
    expose:
      - 80
    depends_on:
      - mariadb

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}-alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379

  maildev:
    container_name: maildev
    image: maildev/maildev:${MAILDEV_VERSION}

volumes:
  https-portal_certs:
  mariadb_data:
  phpmyadmin_sessions:
  redis_data:
