version: "3.5"

services:

  https-portal:
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
    environment:
      - CLIENT_MAX_BODY_SIZE=1024M
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx
      - phpmyadmin

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - 3306

  nginx:
    build:
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    expose:
      - 80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php.dev
      args:
        - PHP_VERSION=${PHP_VERSION}
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    expose:
      - 80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=https://phpmyadmin.dockerbox.test
    volumes:
      - phpmyadmin_sessions:/sessions

  redis:
    image: redis:${REDIS_VERSION}-alpine
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  https-portal_certs:
  mariadb_data:
  phpmyadmin_sessions:
  redis_data:
