version: "3.5"

services:

  https-portal:
    environment:
      DOMAINS: >
        dockerbox.test -> http://nginx:80,
        phpmyadmin.dockerbox.test -> http://phpmyadmin:80,
        maildev.dockerbox.test -> http://maildev:80
      STAGE: local
    networks:
      default:
        aliases:
          - dockerbox.test

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.dev
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./www:/var/www/html:delegated

  php:
    environment:
      - php.display_errors=on
      - php.error_reporting=E_ALL
      - PHP_XDEBUG_REMOTE_ENABLE=1
      - PHP_XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
      - PHP_XDEBUG_REMOTE_PORT=9000
      - PHP_XDEBUG_REMOTE_AUTO_START=1
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=0
      - PHP_XDEBUG_IDEKEY=docker
      - PHP_XDEBUG_PROFILER_ENABLE=0
      - PHP_XDEBUG_PROFILER_OUTPUT_DIR=/tmp
    volumes:
      - ./www:/var/www/html:delegated

  phpmyadmin:
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

  maildev:
    image: djfarrelly/maildev
