version: "3.5"

services:

  bd:
    image: mariadb:10.3
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306

  web:
    build:
      context: .
    depends_on:
      - bd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - bd
    environment:
      - PMA_HOST=bd
      - PMA_PORT=3306

volumes:
  mariadb:
