version: "3.5"

services:

  bd:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306

  web:
    build:
      context: .
    depends_on:
      - bd
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - bd
    environment:
      - PMA_HOST=bd
      - PMA_PORT=3306
    ports:
      - 8080:80

volumes:
  mariadb:
