version: "3.5"

services:

  bd:
    environment:
      - MYSQL_ROOT_PASSWORD=${DEV_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DEV_MYSQL_DATABASE}
      - MYSQL_USER=${DEV_MYSQL_USER}
      - MYSQL_PASSWORD=${DEV_MYSQL_PASSWORD}

  web:
    environment:
      - php.display_errors=on
      - php.error_reporting=E_ALL
      - XDEBUG_REMOTE_ENABLE=1
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
      - XDEBUG_REMOTE_PORT=9000
    volumes:
      - ./www:/app
    ports:
      - ${DEV_WEB_PORT}:80

  phpmyadmin:
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=${DEV_MYSQL_ROOT_PASSWORD}
    ports:
      - ${DEV_PHPMYADMIN_PORT}:80
